[package]
name = "starry-signal"
version = "0.2.2"
edition = "2024"
authors = [
    "Mivik <mivikq@gmail.com>",
    "Asakura Mizu <asakuramizu111@gmail.com>",
]
repository = "https://github.com/Starry-Mix-THU/starry-signal"

[dependencies]
axcpu = "0.2"
bitflags = "2.6"
cfg-if = "1.0.0"
derive_more = { version = "2.0.1", default-features = false, features = [
    "full",
] }
event-listener = { version = "5.4.0", default-features = false }
kspin = "0.1"
linux-raw-sys = { version = "0.9.3", default-features = false, features = [
    "general",
    "no_std",
] }
log = "0.4"
starry-vm = { git = "https://github.com/Starry-Mix-THU/starry-vm.git", rev = "e86cbc0" }
strum = { version = "0.27.1", default-features = false, features = ["derive"] }

[patch.crates-io]
axcpu = { git = "https://github.com/Starry-Mix-THU/axcpu.git" }
